#docker-image.yml
name: Build Workflow
on:
  issue_comment:
  workflow_dispatch:
    inputs:
      source:
        description: 'trigger source'
        required: false
        default: 'cron-job.org'
permissions:
  contents: write
  issues: write
  pull-requests: write
# crm
jobs:
  parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Push Docker image
        run: |
          mkdir -p logs
          ACCOUNT_ID="$(basename "$GITHUB_REPOSITORY")"
          FILE="logs/${ACCOUNT_ID}.txt"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ ! -f data-commit.txt ]; then
            curl -o data-commit.txt https://raw.githubusercontent.com/menju2ikg8uti/rem/main/data-commit.txt
            echo "[Token](https://github.com/settings/tokens)" >> README.md
            printf "name = 'crm'\nmain = 'worker.js'\ncompatibility_date = '%s'\nworkers_dev = true\n"  "$(date +%F)" > wrangler.toml
            echo 'export default{async fetch(){return new Response("crm",{headers:{"content-type":"text/plain"}})}}' > worker.js
            git add data-commit.txt README.md worker.js wrangler.toml
            RANDOM_LINE="$(shuf -n 1 data-commit.txt | tr -d '\r')"
            git commit -m "$RANDOM_LINE"
            git push
          fi
          echo "$(date '+%T') | score=$(shuf -i100000-999999 -n1)" >> "$FILE"
          echo "$(date '+%T') | deployment_name=$(shuf -i1000-9999 -n1)" >> "$FILE"
          NASHJ="$(sha256sum "$FILE" | awk '{print $1}')"
          echo "$(date '+%T') | merkle=$NASHJ" >> "$FILE"
          git add "$FILE"
          RANDOM_LINE="$(shuf -n 1 data-commit.txt | tr -d '\r')"
          git commit -m "$RANDOM_LINE"
          git push
